# Generated by Django 3.1 on 2025-09-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andrekaApp', '0004_auto_20250914_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('cash_on_delivery', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('bkash_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bkash_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bkash_customer_msisdn', models.CharField(blank=True, max_length=20, null=True)),
                ('bkash_merchant_invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='andrekaApp.order')),
            ],
        ),
    ]
