# Generated by Django 3.1 on 2025-09-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andrekaApp', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sslcommerz_bank_tran_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sslcommerz_card_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sslcommerz_card_issuer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sslcommerz_card_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sslcommerz_card_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sslcommerz_session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sslcommerz_store_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sslcommerz_val_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('sslcommerz', 'SSLCOMMERZ'), ('bkash', 'bKash'), ('cash_on_delivery', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
