# Generated by Django 3.1 on 2025-09-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andrekaApp', '0006_auto_20250916_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bkash_customer_msisdn',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bkash_merchant_invoice_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bkash_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bkash_transaction_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('sslcommerz', 'SSLCOMMERZ'), ('cash_on_delivery', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
